### ISSUE TITLE
User creation doesn't work properly

### ISSUE THREAD

**Issue by ChristophShyper** [coopergillan/terraform-provider-redshift#34]
Users having `.` or `-` are not created and providers fails.

This line should have double quotes added and escaped to properly handle allowed usernames.
https://github.com/coopergillan/terraform-provider-redshift/blob/main/redshift/resource_redshift_user.go#L97

**Comment by coopergillan** [comment]
Hi @ChristophShyper - thanks for opening the issue. I wasn't aware those characters were allowed for a username. Are you up for opening a PR for this?

**Comment by ChristophShyper** [comment]
Hi @coopergillan 
Unfortunately I never wrote anything in Go so it will take me some time to set up environment, make changes and write proper tests for it. 
Maybe you or somebody else could do it better?

The change is needed anywhere where username is mentioned and it could be surrounded by a single quotation `'`.

According to https://docs.amazonaws.cn/redshift/latest/APIReference/API_GetClusterCredentials.html
```
Must be 1 to 64 alphanumeric characters or hyphens. The user name can't be PUBLIC.

Must contain only lowercase letters, numbers, underscore, plus sign, period (dot), at symbol (@), or hyphen.

First character must be a letter.

Must not contain a colon ( : ) or slash ( / ).

Cannot be a reserved word. A list of reserved words can be found in Reserved Words in the Amazon Redshift Database Developer Guide.
```

We used emails as usernames (typically what happens when using Single Sign-On), but it was impossible to manage them with this provider.
Also Lambda functions often have `-` in their names and that becomes part of session identifier, hence must equal username in Redshift.

**Comment by coopergillan** [comment]
Thanks for all that information. I will take a look!

**Comment by ChristophShyper** [comment]
Hi. We've created internally our own provider for Redshift and released it recently.
Having this fixed and many other other improvements - https://github.com/brainly/terraform-provider-redshift
